import { Layout } from 'antd';
import { Inter } from 'next/font/google';
import React from 'react';
import LayoutFooter from '../../components/footer/BaseFooter';

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function PoliticalGroupLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <Layout.Content>
        {children}
      </Layout.Content>
      <LayoutFooter />
    </>
  )
}
