'use client';

import { Layout } from 'antd';
import { Inter } from 'next/font/google';
import React from 'react';

import { usePathname } from 'next/navigation';
import '../app/styles/index.scss';
import { LayoutHeader } from './components/header/layoutHeader';

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const pathName = usePathname();

  return (
    <html lang="en">
      <body className={inter.className}>
        <Layout>
          {/* <StyledComponentsRegistry> */}
          <LayoutHeader />
          {children}
          {/* </StyledComponentsRegistry> */}
        </Layout>
      </body>
    </html>
  )
}
