'use client';

import { Layout } from 'antd';
import { Inter } from 'next/font/google';
import React from 'react';
import '../app/styles/index.scss';
import { LayoutHeader } from './components/header/LayoutHeader';

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Layout>
          <LayoutHeader />
          {children}
        </Layout>
      </body>
    </html>
  )
}
