'use client';

import { Layout } from 'antd';
import AboutUsFooter from '../components/about-us/AboutUsFooter';

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function AboutUsLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <Layout.Content className='about-us-section'>
        {children}
      </Layout.Content>
      <AboutUsFooter />
    </>
  )
}
